Alumni page addition
Radiumskull/dscbppimt-official-website pull request #13
Opened 2021-09-18 21:53 UTC by ArkaprabhaChakraborty

solving issue #11. Still some work is left as alumni helper has to be updated. Ill suggest till then this PR can be made a draft.

2021-09-19 18:31 UTC, aniruddha2000 commented
LGTM :-)

2021-09-19 18:40 UTC, aniruddha2000 requested changes
There are the cdn link update the fields with their github url.

2021-09-19 18:40 UTC, aniruddha2000 commented on components/helper/teamHelper.js
> +    {
```
Leads
Arkaprabha - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FarkaprabhaChakraborty.jpeg?alt=media&token=7f3dfa1c-591a-4b1b-a721-d5f48a4a7ab1
Arko - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FarkoSen.jpeg?alt=media&token=3b565ab0-2976-47e5-9f8d-bf2d72a80c40
Rajarshi - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FrajarshiChakraborty.jpeg?alt=media&token=fc295aaf-8032-4816-b513-6161be98c1ac
Rohan - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FrohanRudra.jpeg?alt=media&token=573518b0-f5d2-49f0-9f13-9794e85c1e1e
```

2021-09-19 18:42 UTC, aniruddha2000 commented on components/helper/teamHelper.js
> +    {
Made you the colaborator of DSC interview form where you can take the github link :)

2021-09-19 18:46 UTC, aniruddha2000 requested changes
Update the volunteers and same as above for the GitHub

2021-09-19 18:46 UTC, aniruddha2000 commented on components/helper/teamHelper.js
> +    {
```
Volunteers - 
Ahana - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FahanaBasu.jpeg?alt=media&token=df80987b-e008-4413-b008-8ef2da2bfa4b
Diganta - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FdigantaGhosh.jpeg?alt=media&token=7fd0b914-1dcb-4e12-a177-9d56e8288e8c
Chandrima - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FchandrimaDas.jpeg?alt=media&token=a0de34f8-79c6-40e5-8665-12be58b8b5ae
Maaitryo - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FchandrimaDas.jpeg?alt=media&token=a0de34f8-79c6-40e5-8665-12be58b8b5ae
Shams - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FshamsFiroz.jpeg?alt=media&token=cadf1552-ba8d-41ed-ae34-fcf26204c373
```

2021-09-20 06:57 UTC, aniruddha2000 requested changes
My photo change :)

2021-09-20 06:57 UTC, aniruddha2000 commented on components/helper/teamHelper.js
> +    image : "https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FAniruddhaBasak.jpg?alt=media&token=91019834-b7fa-494e-bd57-c940ebd58cf1",
```suggestion
    image : "https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2FAniruddhaBasak.jpg?alt=media&token=c03d25ab-51d0-4181-b271-6c638130d6dd",
```

2021-09-20 14:28 UTC, aniruddha2000 commented on components/helper/teamHelper.js
> +    {
```
Diganta - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2Fdiganta_ghosh_Y9EpQ81.jpeg?alt=media&token=1161a4e2-159f-464b-9c95-0f6960b9edc4
Debjita - https://firebasestorage.googleapis.com/v0/b/dscbppimt-cms-storage.appspot.com/o/member_images%2Fdebjita_mondal.jpg?alt=media&token=6b96793a-7d90-4eb5-a49f-90e5addf89f9
```
Additional 2 volunteers

2021-09-20 22:40 UTC, ArkaprabhaChakraborty commented
You can merge it now.

2021-09-21 05:29 UTC, aniruddha2000 commented
Ok LGTM :)

2021-09-21 05:29 UTC, merged